# Numpy Arrays

## Basics

In [24]:
import numpy as np

In [25]:
my_list = [1,2,3]
arr=np.array(my_list)
arr

array([1, 2, 3])

In [26]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [31]:
np.random.rand(2,2)  # uses uniform distribution

array([[0.6856165 , 0.58981832],
       [0.51268617, 0.79976538]])

In [32]:
np.random.randint(1,100,10)

array([32, 13, 36, 87, 44, 83, 49, 59, 67, 51])

In [33]:
np.random.randn(2)  #uses normal distribution

array([0.44573346, 0.34736762])

In [34]:
np.random.randn(2,2)

array([[ 0.66578308,  1.68112961],
       [-0.46504419, -1.67613202]])

In [35]:
arr= np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
print(arr.max())

24


In [38]:
print(arr.argmax())   # index

24


In [39]:
print(arr.min())

0


In [40]:
arr.shape

(25,)

In [41]:
arr=arr.reshape(5,5)
arr.shape

(5, 5)

In [43]:
arr.dtype

dtype('int64')

## Numpy Array Indexing

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[8]

np.int64(8)

In [50]:
arr[1:5]

array([1, 2, 3, 4])

In [51]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr[:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr = np.arange(0,11)

In [54]:
sliceOfArray = arr[:6]
sliceOfArray

array([0, 1, 2, 3, 4, 5])

In [55]:
sliceOfArray[:] = 99
sliceOfArray

array([99, 99, 99, 99, 99, 99])

In [58]:
arr 
# Chnages made on slice of array reflect in original array also

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arrCopy = arr.copy()
arrCopy[:]=100
print(arrCopy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99 99  6  7  8  9 10]


In [61]:
arrMat = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrMat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arrMat[2][1]

np.int64(8)

In [64]:
arrMat[2,1]

np.int64(8)

In [65]:
arrMat[:2,1:]

array([[2, 3],
       [5, 6]])

In [66]:
arrMat[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arrMat[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [71]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
boolArr=arr>5

In [74]:
boolArr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr[boolArr]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [77]:
arrMat = np.arange(50).reshape(5,10)

In [78]:
arrMat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
arrMat[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy Operations

In [83]:
arr = np.arange(0,11)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [86]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [88]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [89]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [91]:
arr/arr  
# instead of giving divide by zero error it gives warning

/tmp/ipykernel_60118/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [92]:
1/arr
# 1/0 gives infinity

/tmp/ipykernel_60118/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [94]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [95]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [99]:
np.exp(arr) # computes e to the power x

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [100]:
np.min(arr)

np.int64(0)

In [101]:
np.max(arr)

np.int64(10)

In [102]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [103]:
np.log(arr)

/tmp/ipykernel_60118/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])